### ISSUE TITLE
Canadian Autotrader results

### ISSUE THREAD

**Issue by blakeSaucier** [emastra/autotrader-scraper#5]
Hi,

Is it possible to retrieve results from autotrader.ca? From what I can see the 'REST' api does not exist on the `.ca` domain.

Thanks

**Comment by j624ali** [comment]
Have you found a scraper for the Canadian site?

**Comment by j624ali** [comment]
> Hi,
> 
> Is it possible to retrieve results from autotrader.ca? From what I can see the 'REST' api does not exist on the `.ca` domain.
> 
> Thanks

Hi,
Have you found a scraper for the Canadian site?

**Comment by blakeSaucier** [comment]
I ended up building one from scratch

**Comment by j624ali** [comment]
Cool, is it on your GitHub?

**Comment by blakeSaucier** [comment]
Unfortunately not - the work is owned by my company.
